# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170206_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static', width_field='width_field'),
        ),
    ]
